export const projects = [
  {
    id: 1,
    title: "Barco",
    img: "",
    info: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque lobortis massa, et condimentum dolor congue in. Vivamus tortor diam, vestibulum in luctus quis, commodo ac lectus. Quisque placerat ipsum eu tellus venenatis, sed fermentum sem volutpat. In tempus diam at ultrices pellentesque. Maecenas eu pellentesque diam. Nam sit amet risus leo. Etiam eget orci at est feugiat dictum id ac quam.Vivamus libero nunc, ultrices a leo volutpat, pharetra vulputate augue. Donec varius urna eget risus tincidunt iaculis. Quisque posuere vehicula augue, in facilisis justo blandit at. Duis a dolor vel tortor accumsan volutpat. Etiam eget condimentum ligula. Cras ultrices augue sit amet diam dignissim, sit amet aliquam massa bibendum. Aliquam erat volutpat. Morbi finibus sem a rhoncus placerat.`,
    link: "https://barco-react-app.vercel.app",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 2,
    title: "Delizioso",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 3,
    title: "Google",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 4,
    title: "We Vape",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 5,
    title: "xx",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 6,
    title: "xx",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 7,
    title: "xx",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 8,
    title: "xx",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 9,
    title: "xx",
    img: "",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
];
