export const projects = [
  {
    id: 1,
    title: "Barco",
    info: `This is a website for a Colombian bar hence why its in spanish, it was designed and developed by me. It uses html, css, javascript and React. Some of the elements present on this project are the use of loading states for a better user experience, the items on the menu are renderized using a mock up API so its more dynamic and easier to add or remove new products, it also has working filters so the customers can filter out the type of product they want. Lastly it is fully optimized for desktops and smartphones.`,
    link: "https://barco-react-app.vercel.app",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 2,
    title: "Delizioso",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 3,
    title: "Google",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 4,
    title: "We Vape",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 5,
    title: "xx",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 6,
    title: "xx",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 7,
    title: "xx",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 8,
    title: "xx",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
  {
    id: 9,
    title: "xx",
    info: "info test",
    link: "test link",
    img: "https://img.freepik.com/free-photo/wide-angle-shot-single-tree-growing-clouded-sky-during-sunset-surrounded-by-grass_181624-22807.jpg",
  },
];
